ktor:
  application:
    modules:
      - com.example.ApplicationKt.module

  deployment:
    host: 0.0.0.0
    port: 8080
    sslPort: 8443

  security:
    ssl:
      keyStore: ktor-keystore.p12
      keyAlias: ktor
      keyStorePassword: password
      privateKeyPassword: password
